### PR TITLE
Provide an easier way to use tape-promise.

### PR DESCRIPTION
**Pull request by julien-f**
The user can simply do:

``` js
import test from 'tape-promise/tape'
```

### CODE REVIEW

**Comment by julien-f** [comment]
I did not edit the README because I used GitHub to create the new file.

**Comment by jprichardson** [comment]
Hmm. So have `tape` as an `optionalDependency` in `package.json` then?

**Comment by julien-f** [comment]
Hmm, not necessarily, optional dependencies still specify a compatible ranges and are automatically installed.

The only difference is that if they failed to be installed, the parent package is still successfully installed. I am not sure this semantic fits the case.

**Comment by jprichardson** [comment]
I would list `tape` as a `peerDepedency` but I hate that npm `v2` installs peer dependencies too. Hmm.

**Comment by julien-f** [comment]
IMHO, the easiest and most predictable way is not to add the dependency.

**Comment by julien-f** [comment]
Any news?

**Comment by jprichardson** [comment]
Thanks!

**Pull request merged**
