### PR TITLE
Add t.rejects() and t.doesNotReject()

### LINKED ISSUE #14: Document how to test for promise rejection
My test shall verify that my async function throws, but `t.throws()` doesn't deal with promise results and `t.rejects` is not a function, so which is it?

### PR DESCRIPTION
**Pull request by KayleePop**
fixes https://github.com/jprichardson/tape-promise/issues/14

The assertions return promises that must be awaited in order for the assertions to be passed to tape before t.end() is called.

The returned promise always resolves (doesn't reject) once the assertion has been made.

The default tap messages are `should reject` and `should resolve`

### CODE REVIEW

**Comment by mk-pmb** [comment]
Thanks! I hope this is considered soon.

**Review by RyanZim — APPROVED** [review]
LGTM

**Comment by RyanZim** [comment]
Published in v4.0.0 :tada:

**Comment by mk-pmb** [comment]
Thanks! :+1: :tada:

**Pull request merged**
